
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/report?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root

redis:
  host: 127.0.0.1
  port: 6379
  maxTotal: 500
  maxIdle: 500
  minIdle: 0
  testOnBorrow: false
  testOnReturn: false
server:
  ssl:
    key-store: classpath:gryffindor.xyz.jks
    key-password: 703lk16ow08d
    key-store-type: JKS